// app.js - single-file backend for the demo site
const express = require('express');
const bodyParser = require('body-parser');
const path = require('path');
const { v4: uuid } = require('uuid');

const app = express();
app.use(bodyParser.json());
app.use(express.static(__dirname)); // serves index.html, style.css automatically

// In-memory datasets (demo)
const MENU = [
  { name: "Espresso", price: 120, image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93", description: "Bold & concentrated" },
  { name: "Cappuccino", price: 150, image: "https://images.unsplash.com/photo-1510626176961-4b37d6afc5e3", description: "Velvety milk foam" },
  { name: "Latte", price: 170, image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87", description: "Smooth & creamy" },
  { name: "Cold Brew", price: 180, image: "https://images.unsplash.com/photo-1528825871115-3581a5387919", description: "Slow-steeped chill" }
];

const ORDERS = []; // store orders in memory
const CONTACTS = [];

// API: get menu
app.get('/menu', (req,res) => {
  res.json(MENU);
});

// API: contact
app.post('/contact', (req,res) => {
  const { name, email, message } = req.body || {};
  if(!name || !email){
    return res.status(400).json({ success:false, message:'Name & email required' });
  }
  CONTACTS.push({ id: uuid(), name, email, message, ts: Date.now() });
  console.log('Contact received:', name, email);
  res.json({ success:true, message:'Thanks! We received your message.' });
});

// API: order (checkout)
app.post('/order', (req,res) => {
  const { customer, items } = req.body || {};
  if(!customer || !Array.isArray(items) || items.length===0) {
    return res.status(400).json({ success:false, message:'Invalid order' });
  }
  const id = 'ORD-' + Math.random().toString(36).slice(2,9).toUpperCase();
  const total = items.reduce((s,it)=>s + (it.price * it.qty), 0);
  const order = { id, customer, items, total, ts: Date.now() };
  ORDERS.push(order);
  console.log('Order placed:', id, customer, total);
  res.json({ success:true, id, total });
});

// Admin page (quick view) - simple HTML generated by server
app.get('/admin', (req,res) => {
  let html = `<html><head><title>CAFÉE - Admin</title>
  <style>body{font-family:Arial,Helvetica,sans-serif;background:#fafafa;color:#111;padding:24px} h1{color:#2b2b2b} table{border-collapse:collapse;width:100%} th,td{padding:8px;border:1px solid #ddd} th{background:#222;color:#fff}</style>
  </head><body><h1>CAFÉE Admin</h1>
  <h2>Orders (${ORDERS.length})</h2>`;
  if(ORDERS.length===0) html += '<p>No orders yet.</p>';
  else {
    html += '<table><tr><th>ID</th><th>Customer</th><th>Items</th><th>Total</th><th>Time</th></tr>';
    ORDERS.slice().reverse().forEach(o=>{
      html += <tr><td>${o.id}</td><td>${o.customer}</td><td>${o.items.map(i=>i.name+' x'+i.qty).join('<br>')}</td><td>₹${o.total}</td><td>${new Date(o.ts).toLocaleString()}</td></tr>;
    });
    html += '</table>';
  }
  html += <h2>Contacts (${CONTACTS.length})</h2>;
  if(CONTACTS.length===0) html += '<p>No messages.</p>';
  else {
    html += '<table><tr><th>ID</th><th>Name</th><th>Email</th><th>Message</th><th>Time</th></tr>';
    CONTACTS.slice().reverse().forEach(c=>{
      html += <tr><td>${c.id}</td><td>${c.name}</td><td>${c.email}</td><td>${(c.message||'')}</td><td>${new Date(c.ts).toLocaleString()}</td></tr>;
    });
    html += '</table>';
  }
  html += '</body></html>';
  res.send(html);
});

// fallback to index for client-side routing
app.get('*', (req,res) => res.sendFile(path.join(__dirname, 'index.html')));

// Start
const PORT = process.env.PORT || 3000;
app.listen(PORT, ()=> console.log(🚀 CAFÉE running: http://localhost:${PORT}));
